name: CI Node.js Pipeline M324

on:
  push:
    branches:
      - develop
      - main
      - release/*
      - feature/69-cd
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout Repository
      - uses: actions/checkout@v2

      # Set up Node.js
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./Code/ticketsystem

      # Build project
      - name: Build ticketsystem
        run: npm run build
        working-directory: ./Code/ticketsystem

      # Run tests
      - name: Run Jest tests
        run: npm run testjest
        working-directory: ./Code/ticketsystem

      - name: Run Mocha tests
        run: npm run testmocha
        working-directory: ./Code/ticketsystem

      # Deploy application
      - name: Deploy and start application
        run: |
          cd ./Code/ticketsystem
          npm install
          pm2 delete ticketsystem
          pm2 start npm --name "ticketsystem" -- start
      
