name: CI Node.js Pipeline M324

on:
  push:
    branches:
      - develop
      - main
      - release/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      # Build and test
      - name: Install dependencies for ticketsystem
        run: npm install
        working-directory: ./Code/ticketsystem

      - name: Build ticketsystem
        run: npm run build
        working-directory: ./Code/ticketsystem

      - name: Run Jest tests for ticketsystem
        run: npm run testjest
        working-directory: ./Code/ticketsystem

      - name: Run mocha tests for ticketsystem
        run: npm run testmocha
        working-directory: ./Code/ticketsystem

      - name: Buid Project and Deploy artifacts
        run: npm run build
        working-directory: ./Code/ticketsystem

